export const brands = [
  {
    id: 1,
    imgSrc: "/newSite-images/brand/vanfaba.png",
    alt: "brand",
    width: 174,
    height: 40,
  },
  {
    id: 2,
    imgSrc: "/newSite-images/brand/anvouge.png",
    alt: "brand",
    width: 137,
    height: 30,
  },
  {
    id: 3,
    imgSrc: "/newSite-images/brand/carolin.png",
    alt: "brand",
    width: 129,
    height: 40,
  },
  {
    id: 4,
    imgSrc: "/newSite-images/brand/shangxi.png",
    alt: "brand",
    width: 146,
    height: 40,
  },
  {
    id: 5,
    imgSrc: "/newSite-images/brand/ecomife.png",
    alt: "brand",
    width: 118,
    height: 26,
  },
  {
    id: 6,
    imgSrc: "/newSite-images/brand/cheryl.png",
    alt: "brand",
    width: 110,
    height: 40,
  },
  {
    id: 7,
    imgSrc: "/newSite-images/brand/sopify.png",
    alt: "brand",
    width: 87,
    height: 35,
  },
  {
    id: 8,
    imgSrc: "/newSite-images/brand/pennyw.png",
    alt: "brand",
    width: 127,
    height: 40,
  },
  {
    id: 9,
    imgSrc: "/newSite-images/brand/panadoxn.png",
    alt: "brand",
    width: 157,
    height: 40,
  },
  {
    id: 10,
    imgSrc: "/newSite-images/brand/shangxi.png",
    alt: "brand",
    width: 146,
    height: 40,
  },
];

export const brands2 = [
  {
    id: 1,
    imageSrc: "/newSite-images/brand/vanfaba.png",
    alt: "brand",
    width: 174,
    height: 40,
  },
  {
    id: 2,
    imageSrc: "/newSite-images/brand/anvouge.png",
    alt: "brand",
    width: 137,
    height: 30,
  },
  {
    id: 3,
    imageSrc: "/newSite-images/brand/carolin.png",
    alt: "brand",
    width: 129,
    height: 40,
  },
  {
    id: 4,
    imageSrc: "/newSite-images/brand/shangxi.png",
    alt: "brand",
    width: 146,
    height: 40,
  },
  {
    id: 5,
    imageSrc: "/newSite-images/brand/ecomife.png",
    alt: "brand",
    width: 118,
    height: 26,
  },
  {
    id: 6,
    imageSrc: "/newSite-images/brand/cheryl.png",
    alt: "brand",
    width: 110,
    height: 40,
  },
  {
    id: 7,
    imageSrc: "/newSite-images/brand/sopify.png",
    alt: "brand",
    width: 87,
    height: 35,
  },
  {
    id: 8,
    imageSrc: "/newSite-images/brand/pennyw.png",
    alt: "brand",
    width: 127,
    height: 40,
  },
  {
    id: 9,
    imageSrc: "/newSite-images/brand/panadoxn.png",
    alt: "brand",
    width: 157,
    height: 40,
  },
  {
    id: 1,
    imageSrc: "/newSite-images/brand/vanfaba.png",
    alt: "brand",
    width: 174,
    height: 40,
  },
  {
    id: 2,
    imageSrc: "/newSite-images/brand/anvouge.png",
    alt: "brand",
    width: 137,
    height: 30,
  },
  {
    id: 3,
    imageSrc: "/newSite-images/brand/carolin.png",
    alt: "brand",
    width: 129,
    height: 40,
  },
  {
    id: 4,
    imageSrc: "/newSite-images/brand/shangxi.png",
    alt: "brand",
    width: 146,
    height: 40,
  },
  {
    id: 5,
    imageSrc: "/newSite-images/brand/ecomife.png",
    alt: "brand",
    width: 118,
    height: 26,
  },
  {
    id: 6,
    imageSrc: "/newSite-images/brand/cheryl.png",
    alt: "brand",
    width: 110,
    height: 40,
  },
  {
    id: 7,
    imageSrc: "/newSite-images/brand/sopify.png",
    alt: "brand",
    width: 87,
    height: 35,
  },
  {
    id: 8,
    imageSrc: "/newSite-images/brand/pennyw.png",
    alt: "brand",
    width: 127,
    height: 40,
  },
  {
    id: 9,
    imageSrc: "/newSite-images/brand/panadoxn.png",
    alt: "brand",
    width: 157,
    height: 40,
  },
];

export const brandsChicHaven = [
  {
    id: 1,
    imgSrc: "/newSite-images/brands/brand-01.png",
    alt: "image-brand",
    width: 174,
    height: 62,
  },
  {
    id: 2,
    imgSrc: "/newSite-images/brands/brand-02.png",
    alt: "image-brand",
    width: 174,
    height: 62,
  },
  {
    id: 3,
    imgSrc: "/newSite-images/brands/brand-03.png",
    alt: "image-brand",
    width: 174,
    height: 62,
  },
  {
    id: 4,
    imgSrc: "/newSite-images/brands/brand-04.png",
    alt: "image-brand",
    width: 174,
    height: 62,
  },
  {
    id: 5,
    imgSrc: "/newSite-images/brands/brand-05.png",
    alt: "image-brand",
    width: 174,
    height: 62,
  },
  {
    id: 6,
    imgSrc: "/newSite-images/brands/brand-06.png",
    alt: "image-brand",
    width: 174,
    height: 62,
  },
];
