export const storefrontNavigation = [
  { href: "/", name: "Home" },
  {
    href: "/shop-default-grid",
    name: "Shop",
    children: [
      { href: "/shop-default-grid", name: "All Products" },
      { href: "/search-result", name: "Search" },
      { href: "/shopping-cart", name: "Cart" },
      { href: "/checkout", name: "Checkout" },
    ],
  },
  {
    href: "/shop-default-grid",
    name: "Categories",
    key: "categories",
    active: false,
    children: [
      { href: "/shop-default-grid", name: "All Products", active: false },
    ],
  },
  {
    href: "/FAQs",
    name: "Customer Care",
    children: [
      { href: "/FAQs", name: "FAQs" },
      { href: "/order-tracking", name: "Order Tracking" },
      { href: "/term-of-use", name: "Terms of Use" },
      { href: "/customer-feedback", name: "Customer Feedback" },
      { href: "/store-list", name: "Store List" },
    ],
  },
  { href: "/about-us", name: "About" },
  { href: "/contact", name: "Contact" },
];

export const demoItems = [
  {
    href: "/",
    src: "https://res.cloudinary.com/da9eiiz5f/image/upload/v1764077882/uploads/70291b9374c8c45f265429333db5023b.jpg",
    alt: "home-fashion-womenswear",
    name: "Fashion Womenswear",
    label: ["New", "Trend"],
  },
  {
    href: "/home-fashion-eleganceNest",
    src: "https://res.cloudinary.com/da9eiiz5f/image/upload/v1764077729/uploads/00da853fc3d25b4d1dc4675484b33620.jpg",
    alt: "home-fashion-eleganceNest",
    name: "Fashion EleganceNest",
    label: ["New", "Hot"],
  },
  {
    href: "/home-fashion-main",
    src: "https://res.cloudinary.com/da9eiiz5f/image/upload/v1764077733/uploads/19910b52b474b517e47f0378fc581aab.jpg",
    alt: "home-fashion-main",
    name: "Fashion Main",
    label: ["Hot"],
  },
  {
    href: "/home-fashion-trendset",
    src: "https://res.cloudinary.com/da9eiiz5f/image/upload/v1764077881/uploads/5738444c76e711247743550246ce41e6.jpg",
    alt: "home-fashion-trendset",
    name: "Fashion TrendsetHome",
    label: [],
  },
  {
    href: "/home-fashion-vogueLing",
    src: "https://res.cloudinary.com/da9eiiz5f/image/upload/v1764077731/uploads/9697c1ca1e2bdd4f15e1213bab7670cd.jpg",
    alt: "home-fashion-vogueLiving",
    name: "Fashion VogueLiving",
    label: [],
  },
  {
    href: "/home-fashion-elegantAbode",
    src: "/newSite-images/demo/home-fashion-elegantAbode.jpg",
    alt: "home-fashion-elegantAbode",
    name: "Fashion ElegantAbode",
    label: [],
  },
  {
    href: "/home-fashion-glamDwell",
    src: "/newSite-images/demo/home-fashion-glamDwell.jpg",
    alt: "home-fashion-glamDwell",
    name: "Fashion GlamDwell",
    label: ["New"],
  },
  {
    href: "/home-fashion-classyCove",
    src: "/newSite-images/demo/home-fashion-classycove.jpg",
    alt: "home-fashion-classyCove",
    name: "Fashion ClassyCove",
    label: [],
  },
  {
    href: "/home-fashion-chicHaven",
    src: "/newSite-images/demo/home-fashion-chicHaven.jpg",
    alt: "home-fashion-chicHaven1",
    name: "Fashion ChicHaven 1",
    label: [],
  },
  {
    href: "/home-fashion-chicHaven-02",
    src: "/newSite-images/demo/home-fashion-chicHaven2.jpg",
    alt: "home-fashion-chicHaven2",
    name: "Fashion ChicHaven 2",
    label: [],
  },
  {
    href: "/home-fashion-tiktok",
    src: "/newSite-images/demo/home-fashion-tiktok.jpg",
    alt: "home-fashion-tiktok",
    name: "Fashion TikTok",
    label: [],
  },
  {
    href: "/home-fashion-luxeLiving",
    src: "/newSite-images/demo/home-fashion-luxeLiving.jpg",
    alt: "home-fashion-luxeLiving",
    name: "Fashion LuxeLiving",
    label: [],
  },
  {
    href: "/home-fashion-modernRetreat",
    src: "/newSite-images/demo/home-fashion-modernRetreat.jpg",
    alt: "home-fashion-modernRetreat",
    name: "Fashion ModernRetreat",
    label: [],
  },
  {
    href: "/home-beauty",
    src: "/newSite-images/demo/home-beauty.jpg",
    alt: "home-beauty",
    name: "Beauty",
    label: [],
  },
  {
    href: "/home-skincare",
    src: "/newSite-images/demo/home-skinCare.jpg",
    alt: "home-skincare",
    name: "Skin Care",
    label: [],
  },
  {
    href: "/home-cosmetic",
    src: "/newSite-images/demo/home-cosmetic.jpg",
    alt: "home-cosmetic",
    name: "Cosmetic",
    label: [],
  },
  {
    href: "/home-decor",
    src: "/newSite-images/demo/home-decor.jpg",
    alt: "home-decor",
    name: "Decor",
    label: [],
  },
  {
    href: "/home-furniture",
    src: "/newSite-images/demo/home-furniture.jpg",
    alt: "home-furniture",
    name: "Furniture",
    label: [],
  },
  {
    href: "/home-jewelry-01",
    src: "/newSite-images/demo/home-jewelry.jpg",
    alt: "home-jewelry-elegantGems",
    name: "Jewelry ElegantGems",
    label: [],
  },
  {
    href: "/home-jewelry-02",
    src: "/newSite-images/demo/home-jewelry2.jpg",
    alt: "home-jewelry-glitterGlam",
    name: "Jewelry GlitterGlam",
    label: [],
  },
  {
    href: "/home-activewear",
    src: "/newSite-images/demo/home-activewear.jpg",
    alt: "home-activewear",
    name: "Activewear",
    label: [],
  },
  {
    href: "/home-organic",
    src: "/newSite-images/demo/home-organic.jpg",
    alt: "home-organic",
    name: "Organic",
    label: [],
  },
  {
    href: "/home-sock",
    src: "/newSite-images/demo/home-sock.jpg",
    alt: "home-sock",
    name: "Socks",
    label: [],
  },
  {
    href: "/home-camping",
    src: "/newSite-images/demo/home-camping.jpg",
    alt: "home-camping",
    name: "Camping",
    label: [],
  },
  {
    href: "/home-electronic",
    src: "/newSite-images/demo/home-electronic.jpg",
    alt: "home-electronic",
    name: "Electronic Market",
    label: [],
  },
  {
    href: "/home-pet-store",
    src: "/newSite-images/demo/home-pet-store.jpg",
    alt: "home-pet-store",
    name: "Pet Store",
    label: [],
  },
  {
    href: "/home-pickleball",
    src: "/newSite-images/demo/home-pickleball.jpg",
    alt: "home-pickleball",
    name: "PickleBall",
    label: ["New"],
  },
  {
    href: "/home-sock-2",
    src: "/newSite-images/demo/home-sock2.jpg",
    alt: "home-sock2",
    name: "Socks 2",
    label: ["New"],
  },
  {
    href: "/home-bookstore",
    src: "/newSite-images/demo/home-bookstore.jpg",
    alt: "home-bookstore",
    name: "Bookstore",
    label: ["New"],
  },
  {
    href: "/home-baby",
    src: "/newSite-images/demo/home-baby.jpg",
    alt: "home-baby",
    name: "Baby",
    label: ["New"],
  },
  {
    href: "/home-electronics-store",
    src: "/newSite-images/demo/home-electronic-store.jpg",
    alt: "home-electronic-store",
    name: "Electronics Store",
    label: ["New"],
  },
  {
    href: "/home-sneaker",
    src: "/newSite-images/demo/home-sneaker.jpg",
    alt: "home-sneaker",
    name: "Sneaker",
    label: ["New"],
  },
  {
    href: "/home-gaming",
    src: "/newSite-images/demo/home-gaming-accessory.jpg",
    alt: "home-gaming-accessory",
    name: "Gaming Accessory",
    label: ["New"],
  },
];

export const shopLayout = [
  { href: "/newSite/shop-default-grid", name: "Default Grid" },
  { href: "/shop-default-list", name: "Default List" },
  { href: "/shop-fullwidth-list", name: "Full Width List" },
  { href: "/shop-fullwidth-grid", name: "Full Width Grid" },
  { href: "/shop-left-sidebar", name: "Left Sidebar" },
  { href: "/shop-right-sidebar", name: "Right Sidebar" },
  { href: "/shop-filter-dropdown", name: "Filter Dropdown" },
  { href: "/shop-filter-canvas", name: "Filter Canvas" },
];

export const shopFeatures = [
  { href: "/shop-categories-top", name: "Categories Top 1" },
  { href: "/shop-categories-top-02", name: "Categories Top 2" },
  { href: "/shop-collection", name: "Shop Collection" },
  { href: "/shop-breadcrumb-img", name: "Breadcrumb IMG" },
  { href: "/shop-breadcrumb-left", name: "Breadcrumb Left" },
  { href: "/shop-breadcrumb-background", name: "Breadcrumb BG" },
  { href: "/shop-load-button", name: "Load Button" },
  { href: "/shop-pagination", name: "Pagination" },
  { href: "/shop-infinite-scrolling", name: "Infinite Scrolling" },
];

export const productStyles = [
  { href: "/product-style-01", name: "Product Style 1" },
  { href: "/product-style-02", name: "Product Style 2" },
  { href: "/product-style-03", name: "Product Style 3" },
  { href: "/product-style-04", name: "Product Style 4" },
  { href: "/product-style-05", name: "Product Style 5" },
  { href: "/product-style-06", name: "Product Style 6" },
  { href: "/product-style-07", name: "Product Style 7" },
];

export const otherShopMenus = [
  { href: "/wish-list", name: "Wish List" },
  { href: "/search-result", name: "Search Result" },
  { href: "/shopping-cart", name: "Shopping Cart" },
  { href: "/login", name: "Login/Register" },
  { href: "/forget-password", name: "Forget Password" },
  { href: "/order-tracking", name: "Order Tracking" },
  { href: "/my-account", name: "My Account" },
];

export const productLinks = [
  { href: "/product-detail/68bd91655a23230de929254c", name: "Product Default" },
  { href: "/product-grid-1/68bd91655a23230de929254c", name: "Product Grid1" },
  { href: "/product-grid-2/68bd91655a23230de929254c", name: "Product Grid2" },
  { href: "/product-stacked/68bd91655a23230de929254c", name: "Product stacked" },
  { href: "/product-right-thumbnails/68bd91655a23230de929254c", name: "Product right thumbnails" },
  { href: "/product-bottom-thumbnails/68bd91655a23230de929254c", name: "Product bottom thumbnails" },
  {
    href: "/product-description-accordion/68bd91655a23230de929254c",
    name: "Product Description Accordion",
  },
  { href: "/product-description-list/68bd91655a23230de929254c", name: "Product Description List" },
  {
    href: "/product-description-menutab/68bd91655a23230de929254c",
    name: "Product Description MenuTab",
  },
  {
    href: "/product-description-fullwidth/68bd91655a23230de929254c",
    name: "Product Description Fullwidth",
  },
  { href: "/product-fixed-price/68bd91655a23230de929254c", name: "Product Fixed Price" },
  { href: "/product-fixed-scroll/68bd91655a23230de929254c", name: "Product Fixed Scrolls" },
];

export const swatchLinks = [
  { href: "/product-swatch-color/1", name: "Product Swatch Color" },
  { href: "/product-swatch-rounded/1", name: "Product Swatch Rounded" },
  {
    href: "/product-swatch-rounded-color/1",
    name: "Product Swatch Rounded Colors",
  },
  { href: "/product-swatch-image/1", name: "Product Swatch Image" },
  {
    href: "/product-swatch-rounded-image/1",
    name: "Product Swatch Rounded Image",
  },
  { href: "/product-swatch-dropdown/1", name: "Product Swatch Dropdown" },
  {
    href: "/product-swatch-dropdown-color/1",
    name: "Product Swatch Dropdown Colors",
  },
];

export const productFeatures = [
  {
    href: "/product-frequently-bought-together/2",
    name: "Frequently Bought Together 1",
  },
  {
    href: "/product-frequently-bought-together-02/2",
    name: "Frequently Bought Together 2",
  },
  { href: "/product-up-sell/1", name: "Up Sell" },
  { href: "/product-pre-order/1", name: "Pre-orders" },
  { href: "/product-grouped/1", name: "Grouped" },
  { href: "/product-customer-note/1", name: "Customer Note" },
  { href: "/product-out-of-stock/1", name: "Out Of Stock" },
  { href: "/product-pickup-available/1", name: "Pick Up Available" },
  { href: "/product-variable/1", name: "Variable" },
  { href: "/product-deals/1", name: "Deals" },
  { href: "/product-with-discount/1", name: "With Discount" },
  { href: "/product-external/1", name: "External" },
  { href: "/product-subscribe-save/1", name: "Subscribe Save" },
  { href: "/product-deals-grid/1", name: "Deals Grid", badge: "New" },
  { href: "/product-buyx-gety/1", name: "Buy X Get Y", badge: "New" },
];

export const blogLinks = [
  { href: "/blog-default", name: "Blog Default" },
  { href: "/blog-list", name: "Blog List" },
  { href: "/blog-grid", name: "Blog Grid" },
  { href: "/blog-detail/1", name: "Blog Detail 1" },
  { href: "/blog-detail-02/2", name: "Blog Detail 2" },
];

export const otherPageLinks = [
  { href: "/about-us", name: "About Us" },
  { href: "/store-list", name: "Store List 1" },
  { href: "/store-list-02", name: "Store List 2" },
  { href: "/contact", name: "Contact Us 1" },
  { href: "/contact-02", name: "Contact Us 2" },
  { href: "/404", name: "404" },
  { href: "/FAQs", name: "FAQs" },
  { href: "/term-of-use", name: "Terms Of Use" },
  { href: "/coming-soon", name: "Coming Soon" },
  { href: "/customer-feedback", name: "Customer Feedbacks" },
];
