const modaveTemplate = {
  id: "modave",
  name: "Modave",
  description: "Current active storefront template migrated from newSite components.",
  status: "active",
  selectionMode: "build-time",
  dataSources: {
    home: ["/api/site/home", "/api/site/categories"],
    header: ["/api/site/header"],
    common: ["/api/site/common"],
    productDetail: ["/api/site/product/get-single"],
    productList: ["/api/site/product"],
    order: ["/api/site/order", "/api/site/order/place"],
  },
  routes: {
    home: "/",
    shop: "/shop-default-grid",
    product: "/product-detail/[id]",
    cart: "/shopping-cart",
    checkout: "/checkout",
    search: "/search-result",
    about: "/about-us",
    faq: "/FAQs",
    contact: "/contact",
    login: "/login",
    register: "/register",
    forgotPassword: "/forget-password",
    resetPassword: "/reset-password",
    orderTracking: "/order-tracking",
    terms: "/term-of-use",
    customerFeedback: "/customer-feedback",
    storeList: "/store-list",
    compareProducts: "/compare-products",
    myAccount: "/my-account",
    myAccountAddress: "/my-account-address",
    myAccountOrders: "/my-account-orders",
    myAccountOrderDetails: "/my-account-orders-details",
  },
  pages: {
    home: "HomePage",
    shop: "ShopPage",
    product: "ProductDetailPage",
    cart: "CartPage",
    checkout: "CheckoutPage",
    search: "SearchPage",
    orderConfirm: "OrderConfirmPage",
    orderFailed: "OrderFailedPage",
    about: "AboutPage",
    faq: "FaqPage",
    contact: "ContactPage",
    login: "LoginPage",
    register: "RegisterPage",
    forgotPassword: "ForgotPasswordPage",
    resetPassword: "ResetPasswordPage",
    orderTracking: "OrderTrackingPage",
    terms: "TermsPage",
    customerFeedback: "CustomerFeedbackPage",
    storeList: "StoreListPage",
    compareProducts: "CompareProductsPage",
    myAccount: "MyAccountPage",
    myAccountAddress: "MyAccountAddressPage",
    myAccountOrders: "MyAccountOrdersPage",
    myAccountOrderDetails: "MyAccountOrderDetailsPage",
  },
  homeVariants: {
    default: "home-1",
    available: ["home-1"],
  },
  themeBlocks: [
    "common",
    "header",
    "mainNavigation",
    "latestArrival",
    "highlightedCategories",
    "selectedFeaturedCategories",
    "bestSelling",
    "trending",
    "hotSelling",
    "featuredCollection",
    "shopByCategories",
    "storeLocations",
    "instagramFeed",
    "homeContent",
    "footer",
  ],
};

export default modaveTemplate;
